// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (login, password_hash, totp_secret)
VALUES ($1, $2, $3)
RETURNING id, login, password_hash, totp_secret, created_at, language, email, avatar_object_key, status_text, birthday, find_by_login_visibility, avatar_visibility, birthday_visibility, status_visibility
`

type CreateAccountParams struct {
	Login        string
	PasswordHash string
	TotpSecret   string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Login, arg.PasswordHash, arg.TotpSecret)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.Language,
		&i.Email,
		&i.AvatarObjectKey,
		&i.StatusText,
		&i.Birthday,
		&i.FindByLoginVisibility,
		&i.AvatarVisibility,
		&i.BirthdayVisibility,
		&i.StatusVisibility,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountAvatarKey = `-- name: GetAccountAvatarKey :one
SELECT avatar_object_key FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountAvatarKey(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getAccountAvatarKey, id)
	var avatar_object_key pgtype.Text
	err := row.Scan(&avatar_object_key)
	return avatar_object_key, err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, login, password_hash, totp_secret, created_at, language, email, avatar_object_key, status_text, birthday, find_by_login_visibility, avatar_visibility, birthday_visibility, status_visibility FROM accounts WHERE email = $1
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email pgtype.Text) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.Language,
		&i.Email,
		&i.AvatarObjectKey,
		&i.StatusText,
		&i.Birthday,
		&i.FindByLoginVisibility,
		&i.AvatarVisibility,
		&i.BirthdayVisibility,
		&i.StatusVisibility,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, login, password_hash, totp_secret, created_at, language, email, avatar_object_key, status_text, birthday, find_by_login_visibility, avatar_visibility, birthday_visibility, status_visibility FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.Language,
		&i.Email,
		&i.AvatarObjectKey,
		&i.StatusText,
		&i.Birthday,
		&i.FindByLoginVisibility,
		&i.AvatarVisibility,
		&i.BirthdayVisibility,
		&i.StatusVisibility,
	)
	return i, err
}

const getAccountByLogin = `-- name: GetAccountByLogin :one
SELECT id, login, password_hash, totp_secret, created_at, language, email, avatar_object_key, status_text, birthday, find_by_login_visibility, avatar_visibility, birthday_visibility, status_visibility FROM accounts WHERE login = $1
`

func (q *Queries) GetAccountByLogin(ctx context.Context, login string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByLogin, login)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
		&i.Language,
		&i.Email,
		&i.AvatarObjectKey,
		&i.StatusText,
		&i.Birthday,
		&i.FindByLoginVisibility,
		&i.AvatarVisibility,
		&i.BirthdayVisibility,
		&i.StatusVisibility,
	)
	return i, err
}

const updateAccountAvatar = `-- name: UpdateAccountAvatar :exec
UPDATE accounts SET avatar_object_key = $2 WHERE id = $1
`

type UpdateAccountAvatarParams struct {
	ID              pgtype.UUID
	AvatarObjectKey pgtype.Text
}

func (q *Queries) UpdateAccountAvatar(ctx context.Context, arg UpdateAccountAvatarParams) error {
	_, err := q.db.Exec(ctx, updateAccountAvatar, arg.ID, arg.AvatarObjectKey)
	return err
}

const updateAccountBirthday = `-- name: UpdateAccountBirthday :exec
UPDATE accounts SET birthday = $2 WHERE id = $1
`

type UpdateAccountBirthdayParams struct {
	ID       pgtype.UUID
	Birthday pgtype.Date
}

func (q *Queries) UpdateAccountBirthday(ctx context.Context, arg UpdateAccountBirthdayParams) error {
	_, err := q.db.Exec(ctx, updateAccountBirthday, arg.ID, arg.Birthday)
	return err
}

const updateAccountEmail = `-- name: UpdateAccountEmail :exec
UPDATE accounts SET email = $2 WHERE id = $1
`

type UpdateAccountEmailParams struct {
	ID    pgtype.UUID
	Email pgtype.Text
}

func (q *Queries) UpdateAccountEmail(ctx context.Context, arg UpdateAccountEmailParams) error {
	_, err := q.db.Exec(ctx, updateAccountEmail, arg.ID, arg.Email)
	return err
}

const updateAccountLanguage = `-- name: UpdateAccountLanguage :exec
UPDATE accounts SET language = $2 WHERE id = $1
`

type UpdateAccountLanguageParams struct {
	ID       pgtype.UUID
	Language string
}

func (q *Queries) UpdateAccountLanguage(ctx context.Context, arg UpdateAccountLanguageParams) error {
	_, err := q.db.Exec(ctx, updateAccountLanguage, arg.ID, arg.Language)
	return err
}

const updateAccountPasswordHash = `-- name: UpdateAccountPasswordHash :exec
UPDATE accounts SET password_hash = $2 WHERE id = $1
`

type UpdateAccountPasswordHashParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdateAccountPasswordHash(ctx context.Context, arg UpdateAccountPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateAccountPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateAccountPrivacy = `-- name: UpdateAccountPrivacy :exec
UPDATE accounts SET
    find_by_login_visibility = $2,
    avatar_visibility = $3,
    birthday_visibility = $4,
    status_visibility = $5
WHERE id = $1
`

type UpdateAccountPrivacyParams struct {
	ID                    pgtype.UUID
	FindByLoginVisibility int16
	AvatarVisibility      int16
	BirthdayVisibility    int16
	StatusVisibility      int16
}

func (q *Queries) UpdateAccountPrivacy(ctx context.Context, arg UpdateAccountPrivacyParams) error {
	_, err := q.db.Exec(ctx, updateAccountPrivacy,
		arg.ID,
		arg.FindByLoginVisibility,
		arg.AvatarVisibility,
		arg.BirthdayVisibility,
		arg.StatusVisibility,
	)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
UPDATE accounts SET status_text = $2 WHERE id = $1
`

type UpdateAccountStatusParams struct {
	ID         pgtype.UUID
	StatusText pgtype.Text
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error {
	_, err := q.db.Exec(ctx, updateAccountStatus, arg.ID, arg.StatusText)
	return err
}

const updateAccountTotpSecret = `-- name: UpdateAccountTotpSecret :exec
UPDATE accounts SET totp_secret = $2 WHERE id = $1
`

type UpdateAccountTotpSecretParams struct {
	ID         pgtype.UUID
	TotpSecret string
}

func (q *Queries) UpdateAccountTotpSecret(ctx context.Context, arg UpdateAccountTotpSecretParams) error {
	_, err := q.db.Exec(ctx, updateAccountTotpSecret, arg.ID, arg.TotpSecret)
	return err
}
