// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (login, password_hash, totp_secret)
VALUES ($1, $2, $3)
RETURNING id, login, password_hash, totp_secret, created_at
`

type CreateAccountParams struct {
	Login        string
	PasswordHash string
	TotpSecret   string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Login, arg.PasswordHash, arg.TotpSecret)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const getAccountByLogin = `-- name: GetAccountByLogin :one
SELECT id, login, password_hash, totp_secret, created_at FROM accounts WHERE login = $1
`

func (q *Queries) GetAccountByLogin(ctx context.Context, login string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByLogin, login)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.TotpSecret,
		&i.CreatedAt,
	)
	return i, err
}
