// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_mutes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMutedPeers = `-- name: GetMutedPeers :many
SELECT peer_account_id FROM chat_mutes WHERE account_id = $1
`

func (q *Queries) GetMutedPeers(ctx context.Context, accountID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getMutedPeers, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var peer_account_id pgtype.UUID
		if err := rows.Scan(&peer_account_id); err != nil {
			return nil, err
		}
		items = append(items, peer_account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isChatMuted = `-- name: IsChatMuted :one
SELECT EXISTS(SELECT 1 FROM chat_mutes WHERE account_id = $1 AND peer_account_id = $2)
`

type IsChatMutedParams struct {
	AccountID     pgtype.UUID
	PeerAccountID pgtype.UUID
}

func (q *Queries) IsChatMuted(ctx context.Context, arg IsChatMutedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChatMuted, arg.AccountID, arg.PeerAccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const muteChat = `-- name: MuteChat :exec
INSERT INTO chat_mutes (account_id, peer_account_id)
VALUES ($1, $2)
ON CONFLICT (account_id, peer_account_id) DO NOTHING
`

type MuteChatParams struct {
	AccountID     pgtype.UUID
	PeerAccountID pgtype.UUID
}

func (q *Queries) MuteChat(ctx context.Context, arg MuteChatParams) error {
	_, err := q.db.Exec(ctx, muteChat, arg.AccountID, arg.PeerAccountID)
	return err
}

const unmuteChat = `-- name: UnmuteChat :exec
DELETE FROM chat_mutes WHERE account_id = $1 AND peer_account_id = $2
`

type UnmuteChatParams struct {
	AccountID     pgtype.UUID
	PeerAccountID pgtype.UUID
}

func (q *Queries) UnmuteChat(ctx context.Context, arg UnmuteChatParams) error {
	_, err := q.db.Exec(ctx, unmuteChat, arg.AccountID, arg.PeerAccountID)
	return err
}
