// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getContactAccountIDs = `-- name: GetContactAccountIDs :many
SELECT peer_account_id FROM contacts WHERE account_id = $1
`

func (q *Queries) GetContactAccountIDs(ctx context.Context, accountID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getContactAccountIDs, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var peer_account_id pgtype.UUID
		if err := rows.Scan(&peer_account_id); err != nil {
			return nil, err
		}
		items = append(items, peer_account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isContact = `-- name: IsContact :one
SELECT EXISTS(
    SELECT 1 FROM contacts WHERE account_id = $1 AND peer_account_id = $2
)
`

type IsContactParams struct {
	AccountID     pgtype.UUID
	PeerAccountID pgtype.UUID
}

func (q *Queries) IsContact(ctx context.Context, arg IsContactParams) (bool, error) {
	row := q.db.QueryRow(ctx, isContact, arg.AccountID, arg.PeerAccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertContactsPair = `-- name: UpsertContactsPair :exec
INSERT INTO contacts (account_id, peer_account_id)
VALUES ($1, $2), ($2, $1)
ON CONFLICT DO NOTHING
`

type UpsertContactsPairParams struct {
	AccountID     pgtype.UUID
	PeerAccountID pgtype.UUID
}

func (q *Queries) UpsertContactsPair(ctx context.Context, arg UpsertContactsPairParams) error {
	_, err := q.db.Exec(ctx, upsertContactsPair, arg.AccountID, arg.PeerAccountID)
	return err
}
