// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contact_blocks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockContact = `-- name: BlockContact :exec
INSERT INTO contact_blocks (account_id, peer_account_id)
VALUES ($1, $2)
ON CONFLICT (account_id, peer_account_id) DO NOTHING
`

type BlockContactParams struct {
	AccountID     pgtype.UUID
	PeerAccountID pgtype.UUID
}

func (q *Queries) BlockContact(ctx context.Context, arg BlockContactParams) error {
	_, err := q.db.Exec(ctx, blockContact, arg.AccountID, arg.PeerAccountID)
	return err
}

const getBlockedPeers = `-- name: GetBlockedPeers :many
SELECT peer_account_id FROM contact_blocks WHERE account_id = $1
`

// Кого заблокировал я сам.
func (q *Queries) GetBlockedPeers(ctx context.Context, accountID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getBlockedPeers, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var peer_account_id pgtype.UUID
		if err := rows.Scan(&peer_account_id); err != nil {
			return nil, err
		}
		items = append(items, peer_account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeersWhoBlockedMe = `-- name: GetPeersWhoBlockedMe :many
SELECT account_id FROM contact_blocks WHERE peer_account_id = $1
`

// Кто заблокировал меня.
func (q *Queries) GetPeersWhoBlockedMe(ctx context.Context, peerAccountID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getPeersWhoBlockedMe, peerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var account_id pgtype.UUID
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isBlockedEitherWay = `-- name: IsBlockedEitherWay :one
SELECT EXISTS(
    SELECT 1 FROM contact_blocks
    WHERE (account_id = $1 AND peer_account_id = $2)
       OR (account_id = $2 AND peer_account_id = $1)
)
`

type IsBlockedEitherWayParams struct {
	AccountID     pgtype.UUID
	PeerAccountID pgtype.UUID
}

func (q *Queries) IsBlockedEitherWay(ctx context.Context, arg IsBlockedEitherWayParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlockedEitherWay, arg.AccountID, arg.PeerAccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unblockContact = `-- name: UnblockContact :exec
DELETE FROM contact_blocks WHERE account_id = $1 AND peer_account_id = $2
`

type UnblockContactParams struct {
	AccountID     pgtype.UUID
	PeerAccountID pgtype.UUID
}

func (q *Queries) UnblockContact(ctx context.Context, arg UnblockContactParams) error {
	_, err := q.db.Exec(ctx, unblockContact, arg.AccountID, arg.PeerAccountID)
	return err
}
