// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (account_id, identity_pubkey, device_name, identity_dh_pubkey, identity_dh_signature)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, account_id, identity_pubkey, device_name, last_seen, created_at, identity_dh_pubkey, identity_dh_signature
`

type CreateDeviceParams struct {
	AccountID           pgtype.UUID
	IdentityPubkey      []byte
	DeviceName          pgtype.Text
	IdentityDhPubkey    []byte
	IdentityDhSignature []byte
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.AccountID,
		arg.IdentityPubkey,
		arg.DeviceName,
		arg.IdentityDhPubkey,
		arg.IdentityDhSignature,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.IdentityPubkey,
		&i.DeviceName,
		&i.LastSeen,
		&i.CreatedAt,
		&i.IdentityDhPubkey,
		&i.IdentityDhSignature,
	)
	return i, err
}

const getDevicesByAccount = `-- name: GetDevicesByAccount :many
SELECT id, account_id, identity_pubkey, device_name, last_seen, created_at, identity_dh_pubkey, identity_dh_signature FROM devices WHERE account_id = $1
`

func (q *Queries) GetDevicesByAccount(ctx context.Context, accountID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, getDevicesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.IdentityPubkey,
			&i.DeviceName,
			&i.LastSeen,
			&i.CreatedAt,
			&i.IdentityDhPubkey,
			&i.IdentityDhSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoginByDeviceID = `-- name: GetLoginByDeviceID :one
SELECT a.login
FROM devices d
JOIN accounts a ON a.id = d.account_id
WHERE d.id = $1
`

func (q *Queries) GetLoginByDeviceID(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLoginByDeviceID, id)
	var login string
	err := row.Scan(&login)
	return login, err
}

const updateDeviceLastSeen = `-- name: UpdateDeviceLastSeen :exec
UPDATE devices SET last_seen = now() WHERE id = $1
`

func (q *Queries) UpdateDeviceLastSeen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateDeviceLastSeen, id)
	return err
}
