// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one
INSERT INTO email_verification_tokens (account_id, email, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, email, token_hash, expires_at, attempts, created_at
`

type CreateEmailVerificationTokenParams struct {
	AccountID pgtype.UUID
	Email     string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken,
		arg.AccountID,
		arg.Email,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailVerificationTokensForAccount = `-- name: DeleteEmailVerificationTokensForAccount :exec
DELETE FROM email_verification_tokens WHERE account_id = $1
`

func (q *Queries) DeleteEmailVerificationTokensForAccount(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationTokensForAccount, accountID)
	return err
}

const getLatestEmailVerificationToken = `-- name: GetLatestEmailVerificationToken :one
SELECT id, account_id, email, token_hash, expires_at, attempts, created_at FROM email_verification_tokens
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestEmailVerificationToken(ctx context.Context, accountID pgtype.UUID) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getLatestEmailVerificationToken, accountID)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const incrementEmailVerificationAttempts = `-- name: IncrementEmailVerificationAttempts :exec
UPDATE email_verification_tokens SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementEmailVerificationAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementEmailVerificationAttempts, id)
	return err
}
