// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeedback = `-- name: CreateFeedback :exec
INSERT INTO feedback (account_id, account_login, message)
VALUES ($1, $2, $3)
`

type CreateFeedbackParams struct {
	AccountID    pgtype.UUID
	AccountLogin string
	Message      string
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) error {
	_, err := q.db.Exec(ctx, createFeedback, arg.AccountID, arg.AccountLogin, arg.Message)
	return err
}

const listFeedback = `-- name: ListFeedback :many
SELECT id, account_id, account_login, message, created_at FROM feedback ORDER BY created_at DESC
`

func (q *Queries) ListFeedback(ctx context.Context) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, listFeedback)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feedback
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.AccountLogin,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
