// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite_codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeInviteCode = `-- name: ConsumeInviteCode :one
UPDATE invite_codes
SET used_by_account_id = $2, used_at = now()
WHERE code = $1 AND used_at IS NULL
RETURNING id, code, created_at, used_at, used_by_account_id
`

type ConsumeInviteCodeParams struct {
	Code            string
	UsedByAccountID pgtype.UUID
}

func (q *Queries) ConsumeInviteCode(ctx context.Context, arg ConsumeInviteCodeParams) (InviteCode, error) {
	row := q.db.QueryRow(ctx, consumeInviteCode, arg.Code, arg.UsedByAccountID)
	var i InviteCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedByAccountID,
	)
	return i, err
}

const createInviteCode = `-- name: CreateInviteCode :one
INSERT INTO invite_codes (code) VALUES ($1) RETURNING id, code, created_at, used_at, used_by_account_id
`

func (q *Queries) CreateInviteCode(ctx context.Context, code string) (InviteCode, error) {
	row := q.db.QueryRow(ctx, createInviteCode, code)
	var i InviteCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedByAccountID,
	)
	return i, err
}

const deleteInviteCode = `-- name: DeleteInviteCode :one
DELETE FROM invite_codes WHERE code = $1 RETURNING id, code, created_at, used_at, used_by_account_id
`

func (q *Queries) DeleteInviteCode(ctx context.Context, code string) (InviteCode, error) {
	row := q.db.QueryRow(ctx, deleteInviteCode, code)
	var i InviteCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedByAccountID,
	)
	return i, err
}

const getInviteCodeByCode = `-- name: GetInviteCodeByCode :one
SELECT id, code, created_at, used_at, used_by_account_id FROM invite_codes WHERE code = $1
`

func (q *Queries) GetInviteCodeByCode(ctx context.Context, code string) (InviteCode, error) {
	row := q.db.QueryRow(ctx, getInviteCodeByCode, code)
	var i InviteCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedAt,
		&i.UsedAt,
		&i.UsedByAccountID,
	)
	return i, err
}

const listInviteCodes = `-- name: ListInviteCodes :many
SELECT ic.code, ic.created_at, ic.used_at, a.login AS used_by_login
FROM invite_codes ic
LEFT JOIN accounts a ON a.id = ic.used_by_account_id
ORDER BY ic.created_at DESC
`

type ListInviteCodesRow struct {
	Code        string
	CreatedAt   pgtype.Timestamptz
	UsedAt      pgtype.Timestamptz
	UsedByLogin pgtype.Text
}

func (q *Queries) ListInviteCodes(ctx context.Context) ([]ListInviteCodesRow, error) {
	rows, err := q.db.Query(ctx, listInviteCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInviteCodesRow
	for rows.Next() {
		var i ListInviteCodesRow
		if err := rows.Scan(
			&i.Code,
			&i.CreatedAt,
			&i.UsedAt,
			&i.UsedByLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
