// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMediaFile = `-- name: DeleteMediaFile :exec
DELETE FROM media_files WHERE id = $1
`

func (q *Queries) DeleteMediaFile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMediaFile, id)
	return err
}

const getMediaFile = `-- name: GetMediaFile :one
SELECT id, uploaded_by_account_id, recipient_account_id, object_key, size_bytes, created_at FROM media_files WHERE id = $1
`

func (q *Queries) GetMediaFile(ctx context.Context, id pgtype.UUID) (MediaFile, error) {
	row := q.db.QueryRow(ctx, getMediaFile, id)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.UploadedByAccountID,
		&i.RecipientAccountID,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const saveMediaFile = `-- name: SaveMediaFile :one
INSERT INTO media_files (uploaded_by_account_id, recipient_account_id, object_key, size_bytes)
VALUES ($1, $2, $3, $4)
RETURNING id, uploaded_by_account_id, recipient_account_id, object_key, size_bytes, created_at
`

type SaveMediaFileParams struct {
	UploadedByAccountID pgtype.UUID
	RecipientAccountID  pgtype.UUID
	ObjectKey           string
	SizeBytes           int64
}

func (q *Queries) SaveMediaFile(ctx context.Context, arg SaveMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, saveMediaFile,
		arg.UploadedByAccountID,
		arg.RecipientAccountID,
		arg.ObjectKey,
		arg.SizeBytes,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.UploadedByAccountID,
		&i.RecipientAccountID,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const saveMediaFileWithID = `-- name: SaveMediaFileWithID :one
INSERT INTO media_files (id, uploaded_by_account_id, recipient_account_id, object_key, size_bytes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uploaded_by_account_id, recipient_account_id, object_key, size_bytes, created_at
`

type SaveMediaFileWithIDParams struct {
	ID                  pgtype.UUID
	UploadedByAccountID pgtype.UUID
	RecipientAccountID  pgtype.UUID
	ObjectKey           string
	SizeBytes           int64
}

// докачка по кусочкам (upload_media_chunked.go): id объекта в MinIO выбирает
// сам сервер ещё на шаге /init (до того, как файл целиком долетел), поэтому
// здесь id передаётся явно, а не генерируется базой — строка в БД создаётся
// только при успешном /complete, тот же id, что и ключ объекта в MinIO.
func (q *Queries) SaveMediaFileWithID(ctx context.Context, arg SaveMediaFileWithIDParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, saveMediaFileWithID,
		arg.ID,
		arg.UploadedByAccountID,
		arg.RecipientAccountID,
		arg.ObjectKey,
		arg.SizeBytes,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.UploadedByAccountID,
		&i.RecipientAccountID,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}
