// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message_reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :exec
INSERT INTO message_reports (
    reporter_account_id, reporter_login,
    reported_account_id, reported_login,
    message_text, reason
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateReportParams struct {
	ReporterAccountID pgtype.UUID
	ReporterLogin     string
	ReportedAccountID pgtype.UUID
	ReportedLogin     string
	MessageText       string
	Reason            pgtype.Text
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	_, err := q.db.Exec(ctx, createReport,
		arg.ReporterAccountID,
		arg.ReporterLogin,
		arg.ReportedAccountID,
		arg.ReportedLogin,
		arg.MessageText,
		arg.Reason,
	)
	return err
}

const listReports = `-- name: ListReports :many
SELECT id, reporter_account_id, reporter_login, reported_account_id, reported_login, message_text, reason, created_at FROM message_reports ORDER BY created_at DESC
`

func (q *Queries) ListReports(ctx context.Context) ([]MessageReport, error) {
	rows, err := q.db.Query(ctx, listReports)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageReport
	for rows.Next() {
		var i MessageReport
		if err := rows.Scan(
			&i.ID,
			&i.ReporterAccountID,
			&i.ReporterLogin,
			&i.ReportedAccountID,
			&i.ReportedLogin,
			&i.MessageText,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
