// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           pgtype.UUID
	Login        string
	PasswordHash string
	TotpSecret   string
	CreatedAt    pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
