// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              pgtype.UUID
	Login           string
	PasswordHash    string
	TotpSecret      string
	CreatedAt       pgtype.Timestamptz
	Language        string
	Email           pgtype.Text
	AvatarObjectKey pgtype.Text
}

type ChatMute struct {
	AccountID     pgtype.UUID
	PeerAccountID pgtype.UUID
	CreatedAt     pgtype.Timestamptz
}

type ContactBlock struct {
	AccountID     pgtype.UUID
	PeerAccountID pgtype.UUID
	CreatedAt     pgtype.Timestamptz
}

type Device struct {
	ID                  pgtype.UUID
	AccountID           pgtype.UUID
	IdentityPubkey      []byte
	DeviceName          pgtype.Text
	LastSeen            pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	IdentityDhPubkey    []byte
	IdentityDhSignature []byte
}

type EmailVerificationToken struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	Email     string
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	Attempts  int32
	CreatedAt pgtype.Timestamptz
}

type Feedback struct {
	ID           pgtype.UUID
	AccountID    pgtype.UUID
	AccountLogin string
	Message      string
	CreatedAt    pgtype.Timestamptz
	ReviewedAt   pgtype.Timestamptz
}

type InviteCode struct {
	ID              pgtype.UUID
	Code            string
	CreatedAt       pgtype.Timestamptz
	UsedAt          pgtype.Timestamptz
	UsedByAccountID pgtype.UUID
}

type MediaFile struct {
	ID                  pgtype.UUID
	UploadedByAccountID pgtype.UUID
	RecipientAccountID  pgtype.UUID
	ObjectKey           string
	SizeBytes           int64
	CreatedAt           pgtype.Timestamptz
}

type MessageReport struct {
	ID                pgtype.UUID
	ReporterAccountID pgtype.UUID
	ReporterLogin     string
	ReportedAccountID pgtype.UUID
	ReportedLogin     string
	MessageText       string
	Reason            pgtype.Text
	CreatedAt         pgtype.Timestamptz
	ReviewedAt        pgtype.Timestamptz
}

type OneTimePrekey struct {
	ID        pgtype.UUID
	DeviceID  pgtype.UUID
	Pubkey    []byte
	Used      bool
	CreatedAt pgtype.Timestamptz
}

type PasswordResetToken struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	Attempts  int32
	CreatedAt pgtype.Timestamptz
}

type PendingMessage struct {
	ID         pgtype.UUID
	ToDeviceID pgtype.UUID
	Ciphertext string
	CreatedAt  pgtype.Timestamptz
}

type PushToken struct {
	ID        pgtype.UUID
	DeviceID  pgtype.UUID
	FcmToken  string
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	ID        pgtype.UUID
	AccountID pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type SignedPrekey struct {
	ID        pgtype.UUID
	DeviceID  pgtype.UUID
	Pubkey    []byte
	Signature []byte
	CreatedAt pgtype.Timestamptz
}
