// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: one_time_prekeys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnusedOneTimePrekeys = `-- name: CountUnusedOneTimePrekeys :one
SELECT count(*) FROM one_time_prekeys WHERE device_id = $1 AND used = false
`

func (q *Queries) CountUnusedOneTimePrekeys(ctx context.Context, deviceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedOneTimePrekeys, deviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOneTimePrekeys = `-- name: CreateOneTimePrekeys :many
INSERT INTO one_time_prekeys (device_id, pubkey)
SELECT $1, unnest($2::bytea[])
RETURNING id, device_id, pubkey, used, created_at
`

type CreateOneTimePrekeysParams struct {
	DeviceID pgtype.UUID
	Pubkeys  [][]byte
}

func (q *Queries) CreateOneTimePrekeys(ctx context.Context, arg CreateOneTimePrekeysParams) ([]OneTimePrekey, error) {
	rows, err := q.db.Query(ctx, createOneTimePrekeys, arg.DeviceID, arg.Pubkeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OneTimePrekey
	for rows.Next() {
		var i OneTimePrekey
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Pubkey,
			&i.Used,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
