// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (account_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, account_id, token_hash, expires_at, attempts, created_at
`

type CreatePasswordResetTokenParams struct {
	AccountID pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const deletePasswordResetTokensForAccount = `-- name: DeletePasswordResetTokensForAccount :exec
DELETE FROM password_reset_tokens WHERE account_id = $1
`

func (q *Queries) DeletePasswordResetTokensForAccount(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordResetTokensForAccount, accountID)
	return err
}

const getLatestPasswordResetToken = `-- name: GetLatestPasswordResetToken :one
SELECT id, account_id, token_hash, expires_at, attempts, created_at FROM password_reset_tokens
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPasswordResetToken(ctx context.Context, accountID pgtype.UUID) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getLatestPasswordResetToken, accountID)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Attempts,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPasswordResetAttempts = `-- name: IncrementPasswordResetAttempts :exec
UPDATE password_reset_tokens SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementPasswordResetAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementPasswordResetAttempts, id)
	return err
}
