// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOldPendingMessages = `-- name: DeleteOldPendingMessages :exec
DELETE FROM pending_messages WHERE created_at < $1
`

func (q *Queries) DeleteOldPendingMessages(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldPendingMessages, createdAt)
	return err
}

const deletePendingMessage = `-- name: DeletePendingMessage :exec
DELETE FROM pending_messages WHERE id = $1
`

func (q *Queries) DeletePendingMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingMessage, id)
	return err
}

const deletePendingMessages = `-- name: DeletePendingMessages :exec
DELETE FROM pending_messages WHERE to_device_id = $1
`

func (q *Queries) DeletePendingMessages(ctx context.Context, toDeviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingMessages, toDeviceID)
	return err
}

const getPendingMessages = `-- name: GetPendingMessages :many
SELECT id, to_device_id, ciphertext, created_at FROM pending_messages WHERE to_device_id = $1 ORDER BY created_at
`

func (q *Queries) GetPendingMessages(ctx context.Context, toDeviceID pgtype.UUID) ([]PendingMessage, error) {
	rows, err := q.db.Query(ctx, getPendingMessages, toDeviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingMessage
	for rows.Next() {
		var i PendingMessage
		if err := rows.Scan(
			&i.ID,
			&i.ToDeviceID,
			&i.Ciphertext,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savePendingMessage = `-- name: SavePendingMessage :one
INSERT INTO pending_messages (to_device_id, ciphertext)
VALUES ($1, $2)
RETURNING id
`

type SavePendingMessageParams struct {
	ToDeviceID pgtype.UUID
	Ciphertext string
}

func (q *Queries) SavePendingMessage(ctx context.Context, arg SavePendingMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, savePendingMessage, arg.ToDeviceID, arg.Ciphertext)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
