// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prekey_bundle.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOneTimePrekey = `-- name: ClaimOneTimePrekey :one
UPDATE one_time_prekeys
SET used = true
WHERE id = (
    SELECT otp.id FROM one_time_prekeys otp
    WHERE otp.device_id = $1 AND otp.used = false
    ORDER BY otp.created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, device_id, pubkey, used, created_at
`

func (q *Queries) ClaimOneTimePrekey(ctx context.Context, deviceID pgtype.UUID) (OneTimePrekey, error) {
	row := q.db.QueryRow(ctx, claimOneTimePrekey, deviceID)
	var i OneTimePrekey
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Pubkey,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentityAndSignedPrekey = `-- name: GetIdentityAndSignedPrekey :one
SELECT d.identity_pubkey, d.identity_dh_pubkey, d.identity_dh_signature,
       sp.pubkey AS signed_prekey, sp.signature
FROM devices d
JOIN signed_prekeys sp ON sp.device_id = d.id
WHERE d.id = $1
`

type GetIdentityAndSignedPrekeyRow struct {
	IdentityPubkey      []byte
	IdentityDhPubkey    []byte
	IdentityDhSignature []byte
	SignedPrekey        []byte
	Signature           []byte
}

func (q *Queries) GetIdentityAndSignedPrekey(ctx context.Context, id pgtype.UUID) (GetIdentityAndSignedPrekeyRow, error) {
	row := q.db.QueryRow(ctx, getIdentityAndSignedPrekey, id)
	var i GetIdentityAndSignedPrekeyRow
	err := row.Scan(
		&i.IdentityPubkey,
		&i.IdentityDhPubkey,
		&i.IdentityDhSignature,
		&i.SignedPrekey,
		&i.Signature,
	)
	return i, err
}
