// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePushTokenByDevice = `-- name: DeletePushTokenByDevice :exec
DELETE FROM push_tokens WHERE device_id = $1
`

func (q *Queries) DeletePushTokenByDevice(ctx context.Context, deviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePushTokenByDevice, deviceID)
	return err
}

const getPushTokenByDevice = `-- name: GetPushTokenByDevice :one
SELECT id, device_id, fcm_token, updated_at FROM push_tokens WHERE device_id = $1
`

func (q *Queries) GetPushTokenByDevice(ctx context.Context, deviceID pgtype.UUID) (PushToken, error) {
	row := q.db.QueryRow(ctx, getPushTokenByDevice, deviceID)
	var i PushToken
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.FcmToken,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPushToken = `-- name: UpsertPushToken :exec
INSERT INTO push_tokens (device_id, fcm_token)
VALUES ($1, $2)
ON CONFLICT (device_id) DO UPDATE
SET fcm_token = EXCLUDED.fcm_token, updated_at = now()
`

type UpsertPushTokenParams struct {
	DeviceID pgtype.UUID
	FcmToken string
}

func (q *Queries) UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) error {
	_, err := q.db.Exec(ctx, upsertPushToken, arg.DeviceID, arg.FcmToken)
	return err
}
