// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (account_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, account_id, token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	AccountID pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.AccountID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const extendSession = `-- name: ExtendSession :exec
UPDATE sessions
SET expires_at = $2
WHERE id = $1
`

type ExtendSessionParams struct {
	ID        pgtype.UUID
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.Exec(ctx, extendSession, arg.ID, arg.ExpiresAt)
	return err
}

const getValidSessionByToken = `-- name: GetValidSessionByToken :one
SELECT id, account_id, token_hash, expires_at, created_at FROM sessions
WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) GetValidSessionByToken(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getValidSessionByToken, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeOtherSessions = `-- name: RevokeOtherSessions :exec
DELETE FROM sessions WHERE account_id = $1 AND id != $2
`

type RevokeOtherSessionsParams struct {
	AccountID pgtype.UUID
	ID        pgtype.UUID
}

func (q *Queries) RevokeOtherSessions(ctx context.Context, arg RevokeOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, revokeOtherSessions, arg.AccountID, arg.ID)
	return err
}
