// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signed_prekeys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertSignedPrekey = `-- name: UpsertSignedPrekey :one
INSERT INTO signed_prekeys (device_id, pubkey, signature)
VALUES ($1, $2, $3)
ON CONFLICT (device_id) DO UPDATE
SET pubkey = EXCLUDED.pubkey, signature = EXCLUDED.signature, created_at = now()
RETURNING id, device_id, pubkey, signature, created_at
`

type UpsertSignedPrekeyParams struct {
	DeviceID  pgtype.UUID
	Pubkey    []byte
	Signature []byte
}

func (q *Queries) UpsertSignedPrekey(ctx context.Context, arg UpsertSignedPrekeyParams) (SignedPrekey, error) {
	row := q.db.QueryRow(ctx, upsertSignedPrekey, arg.DeviceID, arg.Pubkey, arg.Signature)
	var i SignedPrekey
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Pubkey,
		&i.Signature,
		&i.CreatedAt,
	)
	return i, err
}
